---
- name: Disable unused filesystems
  lineinfile:
    path: /etc/modprobe.d/CIS.conf
    line: "install cramfs /bin/true"
    create: yes

- name: Set password expiration to 90 days
  lineinfile:
    path: /etc/login.defs
    regexp: '^PASS_MAX_DAYS'
    line: 'PASS_MAX_DAYS   90'

- name: Set minimum password age to 7 days
  lineinfile:
    path: /etc/login.defs
    regexp: '^PASS_MIN_DAYS'
    line: 'PASS_MIN_DAYS   7'
