---
- name: Backup original sshd_config
  copy:
    src: /etc/ssh/sshd_config
    dest: /etc/ssh/sshd_config.bak
    remote_src: yes

- name: Apply hardened SSH config
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    mode: 0600

- name: Restart SSH service
  service:
    name: ssh
    state: restarted
